### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amosmos** [nprutan/shopify-cookieless-auth-demo#2]
Hi,

First of all thanks so much for you work on this and for sharing your findings and demos.

I am just trying to understand the path to build something like this demo.

Did you follow the steps in the Shopify next.js app tutorial and then changed the bits and parts that work with cookie auth to session auth?

I'm asking because I think I see other differences from the app in the tutorial, which seems to be not just cookie\session related. I am trying to understand the best way to develop an app and want to know which path you took with this demo.

Thanks,
Amos

**Comment by nprutan** [comment]
Hi Amos, thanks for the kinds words. I’m glad I can share what I found.

I believe that’s basically the answer to your question as well. I was
initially working on a production app that is on the Shopify App Store. I
started with the Shopify CLI and built the app, but then got rejected
multiple times when submitting the app.

Due to these automated rejections, I dug in and realized that it was
related to the session in Koa. So I thought it was probably a good time to
roll up my sleeves and implement the JWT auth since that’s where Shopify’s
roadmap is headed.

After a ton of trial and error, and using both the tutorial and multiple
forum posts, I settled on the basic architecture that’s in the demo. And
you’re right, there are other changes that are not related to the auth
scenario, but are basically bug fixes that came up during development. Much
of this is related to importing wrong or conflicting packages.

I’ve written a fair amount of JS over the years, but I consider myself more
of a backend, Python dev. So, with that being said, I’m sure there is room
for improvement.

But I’ve got multiple working apps that use the same structure as the demo,
and they are working well so far.

Hope that helps!
Nate
